#!/bin/bash

## SESSION ##
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export XDG_SESSION_TYPE=wayland

## PATH ##
export PATH=$PATH:$HOME/.config/sway
export PATH=$PATH:$HOME/.config/sway/scripts
export PATH=$PATH:$HOME/.local/bin

# WAYLAND APPS #
export MOZ_ENABLE_WAYLAND=1
export GDK_BACKEND=wayland
export QT_QPA_PLATFORM=wayland-egl
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

# THEME #
export QT_QPA_PLATFORMTHEME=qt5ct
export SAL_USE_VCLPLUGIN=kf5

# ZSH
export ZDOTDIR=$HOME/.config/zsh
