#!/bin/bash

## SESSION ##
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export XDG_SESSION_TYPE=wayland

## PATH ##
export PATH=$PATH:$HOME/.config/sway
export PATH=$PATH:$HOME/.config/sway/scripts
export PATH=$PATH:$HOME/.local/bin

# WAYLAND APPS #
export MOZ_ENABLE_WAYLAND=1
export GDK_BACKEND=wayland
export QT_QPA_PLATFORM=wayland-egl
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
export _JAVA_AWT_WM_NONREPARENTING=1

# ZSH
export ZDOTDIR=$HOME/.config/zsh

# THEME #
export QT_QPA_PLATFORMTHEME=qt5ct
export SAL_USE_VCLPLUGIN=kf5
#export XCURSOR_PATH=$HOME/.local/share/icons
#export XCURSOR_THEME=volantes-cursors
#export XCURSOR_SIZE=32

export GTK_THEME=Catppuccin-Mocha-Standard-Peach-Dark:dark

# PORTAL #
# export GTK_USE_PORTAL=1

# export QT_QPA_PLATFORM=xcb
# export GTK_RC_FILES=/etc/gtk/gtkrc:$HOME/.gtkrc:$HOME/.config/gtkrc
# export GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:$HOME/.gtkrc-2.0:$HOME/.config/gtkrc-2.0
# export QT_SCALE_FACTOR=1.2
# export QT_AUTO_SCREEN_SCALE_FACTOR=1
# export QT_FONT_DPI=96
# export QT_AUTO_SCREEN_SCALE_FACTOR=1
# export QT_SCALE_FACTOR=1
# export QT_FONT_DPI=96

# export QT_QPA_PLATFORM=xcb
# export GTK_RC_FILES=/etc/gtk/gtkrc:$HOME/.gtkrc:$HOME/.config/gtkrc
# export GTK2_RC_FILES=/etc/gtk-2.0/gtkrc:$HOME/.gtkrc-2.0:$HOME/.config/gtkrc-2.0
# export QT_SCALE_FACTOR=1.2
# export QT_AUTO_SCREEN_SCALE_FACTOR=1
# export QT_FONT_DPI=96
# export QT_AUTO_SCREEN_SCALE_FACTOR=1
# export QT_SCALE_FACTOR=1
# export QT_FONT_DPI=96

# export DISTRO="MANJARO"
