# i3blocks configuration file
#
# The i3blocks man page describes the usage of the binary,
# and its website describes the configuration:
#
#     https://vivien.github.io/i3blocks


# Global properties
separator=true
separator_block_width=25
command=zsh -i -c 'i3blocks-$BLOCK_NAME'
markup=pango

#[caps]
#full_text="CAPS"
#command=setxkbmap -option caps:none; xdotool key Caps_Lock

#[disk]
#interval=5

#[micro]
#interval=once
#signal=10
#min_width="II 70% "

#[volume]
#interval=5
#signal=10
#min_width="II 70% "

#[profile]
#interval=once

#[disk]
#interval=30
#
#[memory]
#interval=10
#
#[load]
#interval=10

#[wifi]
#interval=5

#[volume]
#interval=once
#signal=10
# min_width="II 70% "

#[brightness]
#interval=once
#signal=10

#[disk]
#interval=60
#command=echo "disk $(df -h / | cut -d " " -f12 | tail -1)"

#[documentation]
#full_text=Documentation
#website=https://vivien.github.io/i3blocks
#command=xdg-open "$website"
#color=#f12711
#
#[greetings]
#color=#f5af19
#command=echo "Hello, $USER!"
#interval=once

[time]
command=echo "<span foreground=\"yellow\"></span> $(date '+%Y-%m-%d %H:%M:%S') "
interval=1

[battery]
interval=5

#[poweroff]
#interval=once
#min_width=25

#[none]
#interval=once
#command=echo ""
