#!/bin/bash

SELF=$0
SWAYPATH="$HOME/.config/sway"

#[[ -e $HOME/.config/zsh/.zshenv ]] && source $HOME/.config/zsh/.zshenv

cmd_init() {
    # PORTALS
    pkill -f "xdg-desktop-portal"
    nohup /usr/libexec/xdg-desktop-portal -r &>/dev/null &
    nohup /usr/libexec/xdg-desktop-portal-gtk -r &>/dev/null &
    nohup /usr/libexec/xdg-desktop-portal-wlr -r &>/dev/null &
    systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
    dbus-update-activation-environment --systemd --all

    # BALOOCTL
    type balooctl &>/dev/null && balooctl disable &>/dev/null

    # NETWORK MANAGER
    # type nmcli &>/dev/null && nmcli radio wifi off
    type nm-applet &>/dev/null && nohup nm-applet &>/dev/null &

    # WALLPAPER
    type nm-applet &>/dev/null && nohup swww init &>/dev/null &
    desktop wallpaper

    # VBOX
    # type VBoxClient &>/dev/null && VBoxClient --clipboard

    exit 0
}

cmd_panel() {
    #export XDG_CURRENT_DESKTOP=Unity
    pkill waybar
    exec waybar -c $HOME/.config/waybar/config -s $HOME/.config/waybar/style.css "$@"
}

cmd_wallpaper() {
  local image=$(ls ~/.local/share/backgrounds | shuf -n 1)
  if type swww &>/dev/null; then
    swww img $HOME/.local/share/backgrounds/${image} \
      --transition-type center \
      --transition-fps 60 \
      --transition-step 50 \
      --transition-duration 1
    # swww img $HOME/.local/share/backgrounds/sunset-synthwave-sports-car-city-palm-trees.jpg
  else
    swaymsg output '*' bg $HOME/.local/share/backgrounds/${image} fill
    # swaymsg output * bg #1e1e2e solid_color
  fi
}

cmd_hyprland_monitor_menu() {
  local monitors=$(hyprctl monitors all -j | jq -r '.[].name')
  local monitor=$(hyprctl monitors all -j | jq -r '.[].name' | rofi -dmenu)
  hyprctl keyword monitor ${monitor},preferred,auto,1
  for m in ${monitors}; do
    hyprctl keyword monitor ${m},disable
  done
}

cmd_monitors() {
  local screens external internal
  local selected default

  screens=$(swaymsg -t get_outputs | jq -r '.[].name' | sort)
  default="$(swaymsg -t get_outputs | jq -r '.[].name' | grep "eDP" | head -1)"

  # Criteria one
  #external=$(swaymsg -t get_outputs | jq -r '.[].name' | grep "HDMI" | head 0)
  #internal=$(swaymsg -t get_outputs | jq -r '.[].name' | grep "eDP" | head -1)

  #[ -n "$external" ] && selected="$external"
  #[ -z "$external" ] && selected="$internal"

  # Criteria two
  selected="$(swaymsg -t get_outputs | jq -r '.[].name' | sort | grep -v "eDP" | head -1)"
  [ -z "$selected" ] && selected="$default"

  echo $selected
  for screen in $(echo "$screens"); do
    if [ "$screen" = "$selected" ]; then
      swaymsg output $screen enable
      swaymsg output $screen resolution "1920x1080" position "0,0" scale 1
    else
      swaymsg output $screen disable
    fi
  done

  desktop wallpaper
}

cmd_hyprland_settheme() {
  local gnome_schema="org.gnome.desktop.interface"
  local cursor_theme="bibata-modern-ice-cursors"
  local gtk_theme="Catppuccin-Mocha-Standard-Peach-Dark"
  local icon_theme="cupertino-sonoma-icons"
  local font_theme="JetBrainsMono Nerd Font 14"

  [ -d "$HOME/.local/share/icons/${cursor_theme}" ] && \
    hyprctl setcursor "${cursor_theme}" 24 \

  ! type gsettings &>/dev/null && exit 0

  [ -d "$HOME/.local/share/icons/${cursor_theme}" ] && \
    gsettings set ${gnome_schema} cursor-theme "${cursor_theme}"

  [ -d "$HOME/.local/share/themes/${gtk_theme}" ] && \
    gsettings set ${gnome_schema} gtk-theme "${gtk_theme}"
    gsettings set ${gnome_schema} color-scheme 'prefer-dark'

  [ -d "$HOME/.local/share/themes/icons/${icon_theme}" ] && \
    gsettings set ${gnome_schema} icon-theme "${icon_theme}"

  gsettings set ${gnome_schema} font-name "${font_theme}"

  exit 0
}

function cmd_locking() {
    local image=$1

    swaylock \
    --ignore-empty-password \
    --show-failed-attempts \
    --indicator-radius 50 \
    -f -i $image -s fill
}

menu() {
  local cmd="wofi"
  type rofi &>/dev/null && cmd="rofi"
  exec wofi -i --dmenu --no-actions --normal-window --allow-images -s $HOME/.config/sway/wofi.css
}

function cmd_menu() {
    type rofi &>/dev/null && exec rofi -show drun
    [ -n "$(pidof wofi)" ] && return 0
    exec wofi -i --show drun \
        --no-actions \
        --normal-window \
        --allow-images \
        --sort-order=alphabetical \
        --parse-search \
        --lines=10 --columns=10 \
        -s $HOME/.config/sway/wofi.css
        #--matching=fuzzy \
}


function cmd_menu-power() {
    swaymsg exit
    #local opt=$(printf "LOGOUT\nREBOOT\nPOWEROFF" | menu)
    #[ "$opt" = "LOGOUT" ] && swaymsg exit
    #[ "$opt" = "REBOOT" ] && systemctl reboot
    #[ "$opt" = "POWEROFF" ] && systemctl poweroff
}

function cmd_pass {
    local commands=("init" "ls" "grep" "find" "show" "insert" "edit" "generate" "rm" "mv" "cp" "git" "otp")
    local args=( "$@" )
    local pos=()
    local clip=false
    local rc

    while [[ $# -gt 0 ]]; do
        case $1 in
            -c|--clip)
                clip=true
                shift
                ;;
            -*)
                shift
                ;;
            *)
                pos+=("$1")
                shift
                ;;
        esac
    done

    set -- "${args[@]}"

    if [[ "$1" = "list" ]]; then
        find $PASSWORD_STORE_DIR -type f,l -name \*.gpg | sed "s#$PASSWORD_STORE_DIR/*##g" | sed 's/\.gpg$//g'
    elif [[ "${commands[@]}" =~ "$1" ]]; then
        command pass "$@"
    else
        if [ -z "${pos[1]}" ]; then
            command pass "$@"
        else
            if [ "${pos[1]}" = "password" ]; then
                rc=$(pass "${pos[0]}" | head -1)
                [ -z "$rc" ] && return 1
                [ "$clip" = "true" ] && echo $rc | wl-copy -n && return 0
                echo $rc
            elif [ "${pos[1]}" = "otpauth" ] || [ "${pos[1]}" = "otp" ]; then
                if [ "$clip" = "true" ]; then
                    command pass otp -c "${pos[0]}"
                else
                    command pass otp "${pos[0]}"
                fi
            else
                rc=$(pass "${pos[0]}" | grep "^${pos[1]}:" | sed "s/^${pos[1]}: *//g" | tr '\n' ' ' | sed 's/ *$//g')
                [ -z "$rc" ] && return 1
                [ "$clip" = "true" ] && echo $rc | wl-copy -n && return 0
                echo $rc
            fi
        fi
    fi
}

function cmd_menu-pass() {
    local entry entries
    local subvalue subvalues

    entries=$(cmd_pass list)
    entry=$(printf "$entries" | menu)

    subvalues=$(cmd_pass $entry | grep -n "^[a-zA-Z0-9]*:.*$" | cut -d ":" -f 1,2)
    if [ -n "$subvalues" ]; then
        subvalue=$(printf "1:password\n$subvalues" | menu)
        cmd_pass -c $entry $(echo $subvalue | cut -d":" -f 2)
    else
        cmd_pass show -c $entry
    fi
}

cmd_terminal() {
  export ZDOTDIR=$HOME/.config/zsh
  if [ -z "${1}" ]; then
    type alacritty &>/dev/null && exec alacritty -e ${SELF} terminal shell
    type wezterm &>/dev/null && exec wezterm start --always-new-process -- ${SELF} terminal shell
    type foot &>/dev/null && exec foot
  else
    # ZELLIJ
    if type zellij &>/dev/null; then
      { zellij attach '0' || exec zellij -s '0'; }; exit 0
    fi

    # TMUX
    if type tmux &>/dev/null; then
      { tmux attach-session -t '0' || exec tmux -2 new-session -s '0' -n 'HOME'; }; exit 0
    fi

    # ZSH
    type zsh &>/dev/null && exec zsh
  fi
}

main() {
    local args="$@"
    local command="$1"
    local desktop=${XDG_CURRENT_DESKTOP,,}

    [ "$args" = "-b bar-0" ] && cmd_waybar "$@"

    shift
    if type cmd_${desktop}_${command} &>/dev/null; then
      cmd_${desktop}_${command} "$@"
    elif type cmd_$command &>/dev/null; then
      cmd_${command} "$@"
    else
      echo "Command ${command} do not exists"
      exit 1
    fi
}

main "$@"
