#!/usr/bin/zsh

dot() {
  command git --git-dir=$HOME/.local/share/settings --work-tree=$HOME "$@"
}

dot-get-windows-files() {
  local windows_user_home=$(echo $PATH | grep -io -P "/mnt/c/Users/.*?/" | head -1)

  [ -z "${windows_user_home}" ] && return 0
  [ ! -d "$HOME/.config/Windows" ] && mkdir -p $HOME/.config/Windows

  cp $windows_user_home/AppData/Roaming/Code/User/settings.json \
    $HOME/.config/Windows/code-user-settings.json

  cp $windows_user_home/AppData/Roaming/Code/User/keybindings.json \
    $HOME/.config/Windows/code-user-keybindings.json

  cp $windows_user_home/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json \
    $HOME/.config/Windows/terminal-settings.json
}

status() {
  dot restore --staged . &>/dev/null

  # ADD WINDOWS FILE (WSL)
  dot-get-windows-files
  ###

  [ -e "$KUBECONFIG" ] && \
    sed "s/current-context:.*$/current-context: none/g" -i $KUBECONFIG

  # add
  set +e
  {
    dot add -u
    dot add $HOME/.bashrc
    dot add $HOME/.gitignore
    dot add $HOME/.config/autostart
    dot add $HOME/.config/zsh
    dot add $HOME/.config/nvim
    dot add $HOME/.config/helix
    dot add $HOME/.config/tmux
    dot add $HOME/.config/nix
    dot add $HOME/.config/zellij
    dot add $HOME/.config/alacritty
    dot add $HOME/.config/kitty
    dot add $HOME/.config/foot
    dot add $HOME/.config/wezterm
    dot add $HOME/.config/git
    dot add $HOME/.config/kube/config
    dot add $HOME/.config/wsl
    dot add $HOME/.config/qtile
    dot add $HOME/.config/sway
    dot add $HOME/.config/hypr
    dot add $HOME/.config/gnome
    dot add $HOME/.config/waybar
    dot add $HOME/.config/rofi
    dot add $HOME/.config/mutt
    dot add $HOME/.config/systemd
    dot add $HOME/.config/mako
    dot add $HOME/.config/dunst
    dot add $HOME/.config/zsh
    dot add $HOME/.config/scripts
    dot add $HOME/.config/just
    dot add $HOME/.config/starship.toml
    dot add $HOME/.config/containers
    dot add $HOME/.config/distrobox
    dot add $HOME/.config/i3
    dot add $HOME/.config/pylintrc
    dot add $HOME/.config/gnupg/gpg.conf
    dot add $HOME/.config/gnupg/gpg-agent.conf
    dot add $HOME/.config/Windows
    dot add $HOME/.config/Code/User/settings.json
    dot add $HOME/.config/Code/User/keybindings.json
    dot add $HOME/.ssh/config
    dot add $HOME/.aws/config
    dot add $HOME/.config/k9s
    dot add $HOME/.var/app/com.google.Chrome/config/chrome-flags.conf
    dot add $HOME/.var/app/com.brave.Browser/config/brave-flags.conf
    dot add $HOME/.local/share/flatpak/overrides/global
    dot add $HOME/.local/share/themes
    dot add $HOME/.local/share/backgrounds
    dot add $HOME/.local/share/icons/*icons
    dot add $HOME/.local/share/icons/*cursors
    dot add $HOME/.local/share/fonts/*.ttf
    #dot add $HOME/.local/share/fonts/*.otf
  } &>/dev/null
  set -e

  # status
  dot status
}

save() {
  dot commit -m "Commit on '$(date '+%Y-%m-%d %H:%M:%S')'"
  dot push -u origin main
}

load() {
  dot pull
}

[ "$1" = "changes" ] && exec status
[ "$1" = "save" ] && exec save
[ "$1" = "load" ] && exec load
exec dot "$@"

