#!/usr/bin/zsh

main() {
  local entry=$(find . -path "*/overlays/*" -type f -name kustomization.yaml | xargs -I@ dirname @ | fzf)
  [ -z "$entry" ] && return 0

  local context=$(basename $(echo ${entry} | grep -o ".*overlays/[a-zA-Z0-9]*"))

  if [ "${1}" = "apply" ]; then
    #print -z kubectl --context $(basename $entry) apply --server-side --force-conflicts -k ${entry}
    #print -z "kustomize build --enable-alpha-plugins ${entry} | kubectl --context $(basename $entry) apply --server-side --force-conflicts -f -"
    print -z "kustomize build --enable-helm ${entry} | kubectl --context ${context} apply --server-side --force-conflicts -f -"
  elif [ "${1}" = "diff" ]; then
    print -z "kustomize build --enable-helm ${entry} | kubectl --context ${context} diff --server-side --force-conflicts -f -"
  elif [ "${1}" = "bundle" ]; then
    print -z "kustomize build --enable-helm ${entry} | tee ${entry}/bundle.yaml"
  fi
}

main "$@"
