# PROMPT
#SPACESHIP_PROMPT_ORDER=(user host dir git venv aws kubectl async line_sep char)
SPACESHIP_PROMPT_ORDER=(user host dir git venv aws async line_sep char)

# TIME
SPACESHIP_TIME_SHOW=true

# USER
SPACESHIP_USER_SHOW=always

# HOST
SPACESHIP_HOST_SHOW="always"

# DIR
SPACESHIP_DIR_TRUNC_REPO=false
SPACESHIP_DIR_TRUNC=0

# AWS
SPACESHIP_AWS_SHOW=true
SPACESHIP_AWS_PREFIX="aws"
SPACESHIP_AWS_SYMBOL=" "

# K8s
SPACESHIP_KUBECTL_SHOW=true
SPACESHIP_KUBECTL_VERSION_SHOW=false
SPACESHIP_KUBECTL_SYMBOL="☸️  "

# PYTHON
SPACESHIP_VENV_PREFIX="virtualenv"
SPACESHIP_VENV_SYMBOL=" "
