# PROMPT
SPACESHIP_PROMPT_ORDER=(user host dir git aws kubectl async line_sep char)

# TIME
SPACESHIP_TIME_SHOW=true

# USER
SPACESHIP_USER_SHOW=always

# HOST
SPACESHIP_HOST_SHOW="always"

# DIR
SPACESHIP_DIR_TRUNC_REPO=false
SPACESHIP_DIR_TRUNC=0

# AWS
SPACESHIP_AWS_SHOW=true
#SPACESHIP_AWS_PREFIX="using aws "
SPACESHIP_AWS_SYMBOL="☁️  "
