
[private]
default:
  echo nothing

tunnel-db-demosign:
  kubectl --context demo -n default port-forward pods/forward-0 5432:5432
  #aws ssm start-session --cli-read-timeout 8000 \
  #--target i-01acfa654c4bee359 \
  #--document-name AWS-StartPortForwardingSessionToRemoteHost \
  #--parameters '{"host":["demosign.cmu2qzz9znmw.eu-south-2.rds.amazonaws.com"],"portNumber":["5432"],"localPortNumber":["5432"]}' \
  #--profile demo

tunnel-db-demo:
  kubectl --context demo -n default port-forward pods/forward-0 1522:1521

tunnel-db-new-test:
  kubectl --context dev -n testing port-forward pods/forward-0 1523:1521

tunnel-db-prod:
  kubectl --context prod -n default port-forward pods/forward-0 1525:1521

tunnel-db-backoffice:
  kubectl --context prod -n default port-forward pods/forward-0 5434:5434

tunnel-db-prod-logalsend:
  kubectl --context prod -n default port-forward pods/forward-0 1526:1522

tunnel-db-test:
  aws ssm start-session --cli-read-timeout 8000 \
  --target i-04a7f8ed6a1c77a37 \
  --document-name AWS-StartPortForwardingSessionToRemoteHost \
  --parameters '{"host":["logalty.chfbhhgsmzca.eu-south-2.rds.amazonaws.com"],"portNumber":["1521"],"localPortNumber":["1523"]}' \
  --profile qa

tunnel-db-mutua:
  aws ssm start-session --cli-read-timeout 8000 \
  --target i-0de20ea701c7b5a58 \
  --document-name AWS-StartPortForwardingSessionToRemoteHost \
  --parameters '{"host":["mutua.c8yct6jx3mwh.eu-west-1.rds.amazonaws.com"],"portNumber":["5432"],"localPortNumber":["5432"]}' \
  --profile mutua

tunnel-db-ireland:
  aws ssm start-session --cli-read-timeout 8000 \
  --target i-0837b768596c26989 \
  --document-name AWS-StartPortForwardingSessionToRemoteHost \
  --parameters '{"host":["pro-db-lgtid.cw9jeidr8a9e.eu-west-1.rds.amazonaws.com"],"portNumber":["1521"],"localPortNumber":["1526"]}' \
  --profile ireland



tunnel-db-connect-demo:
  kubectl --context demo -n default port-forward pods/forward-0 5433:5433

tunnel-db-connect-prod:
  kubectl --context prod -n default port-forward pods/forward-0 5433:5433

tunnel-db-releases:
  kubectl --context tools -n logalty port-forward pods/mysql-0 3306:3306

tunnel-db-mongodb:
  echo kubectl --context demo -n mongodb port-forward pods/mongo-0 27017
  echo kubectl --context demo -n mongodb port-forward pods/mongo-1 27017
  echo kubectl --context demo -n mongodb port-forward pods/mongo-2 27017

tunnel-db-secure:
  aws ssm start-session --cli-read-timeout 8000 \
  --target i-06fbe4d9a69550d27 \
  --document-name AWS-StartPortForwardingSessionToRemoteHost \
  --parameters '{"host":["logteca.cdl88pofwdpb.eu-west-1.rds.amazonaws.com"],"portNumber":["1521"],"localPortNumber":["1521"]}' \
  --profile secure --region eu-west-1

demo-mongodb-0:
  kubectl --context demo -n mongodb exec -it pod/mongo-0 -c mongo -- bash -c 'mongo -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD'

demo-mongodb-1:
  kubectl --context demo -n mongodb exec -it pod/mongo-1 -c mongo -- bash -c 'mongo -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD'

demo-mongodb-2:
  kubectl --context demo -n mongodb exec -it pod/mongo-2 -c mongo -- bash -c 'mongo -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD'

demo-boidas-db:
  kubectl --context demo -n boidas port-forward pods/postgresql-0 5432:5432

boidas-prod:
  aws ssm start-session --cli-read-timeout 8000 --target i-02147036908fa4347 --document-name AWS-StartPortForwardingSessionToRemoteHost  --parameters '{"host":["lgt-pg-prod.cw9jeidr8a9e.eu-west-1.rds.amazonaws.com"],"portNumber":["5432"],"localPortNumber":["5436"]}'  --profile ireland

vpn-globalprotect:
  sudo openconnect --protocol=gp \
    -u miguellopez \
    -c $HOME/Documents/Certificates/logalty.vpn.cliente.sistemas.pem \
    --servercert pin-sha256:o5uZ5Kl+5Cg/tDzWHiIOPHR8Y7rq7wXc7IuX9lLbnkM= \
    194.140.17.69

vpn-globalprotect-host:
  distrobox-host-exec sudo openconnect --protocol=gp \
    -u miguellopez \
    -c $HOME/Documents/Certificates/logalty.vpn.cliente.sistemas.pem \
    --servercert pin-sha256:o5uZ5Kl+5Cg/tDzWHiIOPHR8Y7rq7wXc7IuX9lLbnkM= \
    194.140.17.69

vpn-fortinet-gui:
  distrobox-host-exec /bin/bash -c 'GDK_BACKEND=x11 DISPLAY=:0 /opt/forticlient/gui/FortiClient-linux-x64/FortiClient'

vpn-fortinet-host:
  distrobox-host-exec sudo openconnect --protocol=fortinet -u miguel.lopez madrid.logalty.com:10443

argocd-dev:
  kubectl --context dev -n argocd port-forward svc/argocd-server 8080:80

argocd-demo:
  kubectl --context demo -n argocd port-forward svc/argocd-server 8080:80

argocd-prod:
  kubectl --context prod -n argocd port-forward svc/argocd-server 8080:80

argocd-tools:
  kubectl --context tools -n argocd port-forward svc/argocd-server 8080:80

prometheus-demo:
  kubectl --context demo -n monitoring port-forward pod/prometheus-prometheus-0 9090:9090

sqlline-install:
  #!/bin/bash
  ver=1.12.0
  cd $HOME/.local/bin/
  wget https://repo1.maven.org/maven2/sqlline/sqlline/$ver/sqlline-$ver-jar-with-dependencies.jar
  wget https://download.oracle.com/otn-pub/otn_software/jdbc/233/ojdbc11.jar

connect-secure-bus:
  #!/bin/bash
  trap 'kill $(jobs -p)' EXIT
  cd $HOME/.local/bin/
  #java -cp "*" sqlline.SqlLine -n COREBUS -p "dOn90Brick#" -u "jdbc:oracle:thin:@//logteca.cdl88pofwdpb.eu-west-1.rds.amazonaws.com:1521/LOGTECA"
  ssh -N -L 15342:logteca.cdl88pofwdpb.eu-west-1.rds.amazonaws.com:1521 secure-bastion &
  sleep 3
  java -cp "*" sqlline.SqlLine -n COREBUS -p "dOn90Brick#" -u "jdbc:oracle:thin:@//localhost:15342/LOGTECA"

ecr-login:
 aws ecr get-login-password --profile production | docker login --username AWS --password-stdin 234166862235.dkr.ecr.eu-south-2.amazonaws.com
