#####################
### CONFIGURATION ###
#####################

set -g default-command "/usr/bin/zsh"
set -g default-terminal 'screen-256color'
set -g terminal-overrides ',*:Tc'
set -g history-limit 10000
set -g allow-rename off
set -g automatic-rename off
set -g mode-keys vi
set -g base-index 1
set -g renumber-windows on
set -g escape-time 10
set -g focus-events on

unbind C-b
set -g prefix C-a
bind C-a send-prefix

unbind 'c'
unbind '"'
unbind '%'

bind n new-window
bind h split-window -h -c '#{pane_current_path}'
bind v split-window -v -c '#{pane_current_path}'
bind y setw synchronize-panes off
bind f resize-pane -Z
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded"
bind Space copy-mode

bind j select-pane -L
bind k select-pane -D
bind l select-pane -U
bind ñ select-pane -R

bind -r > swap-window -t -1 \; previous-window
bind -r < swap-window -t +1 \; next-window

bind -n C-n new-window
bind -n C-h split-window -h -c '#{pane_current_path}'
bind -n C-v split-window -v -c '#{pane_current_path}'
bind -n C-y setw synchronize-panes off
bind -n C-f resize-pane -Z
bind -n C-r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded"
bind -n C-Space copy-mode

bind -n C-j select-pane -L
bind -n C-k select-pane -D
bind -n C-l select-pane -U
bind -n C-ñ select-pane -R

bind -n M-h select-pane -l -Z

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 10

# bind -n M-Tab   next-window
# bind -n M-S-Tab previous-window

bind -n -r C-M-j   resize-pane -L
bind -n -r C-M-k   resize-pane -D
bind -n -r C-M-l   resize-pane -U
bind -n -r C-M-ñ   resize-pane -R
bind -n -r C-Left  resize-pane -L
bind -n -r C-Down  resize-pane -D
bind -n -r C-Up    resize-pane -U
bind -n -r C-Right resize-pane -R

## THEMES
run-shell "~/.config/tmux/themes/nord/nord.tmux"
set -g status-position bottom
set -g status-justify centre
