#####################
### CONFIGURATION ###
#####################

set -g default-command "/usr/bin/zsh"
set -g default-terminal 'screen-256color'
set -g terminal-overrides ',*:Tc'
set -g history-limit 10000
set -g allow-rename off
set -g automatic-rename off
#set -g mode-keys vi
set -g base-index 1
set -g renumber-windows on
set -g escape-time 10
set -g focus-events on
#setw -g xterm-keys on

unbind C-b; set -g prefix None 
# bind C-a send-prefix

bind -n M-n new-window
bind -n M-h split-window -h -c '#{pane_current_path}'
bind -n M-v split-window -v -c '#{pane_current_path}'
bind -n M-y setw synchronize-panes off
bind -n M-f resize-pane -Z
bind -n M-r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded"
bind -n M-o copy-mode
bind -n M-, command-prompt -I "#W" "rename-window '%%'"
bind -n M-u kill-pane
bind -n M-q kill-pane
bind -n M-m select-pane -l -Z

bind -n -r C-Left  swap-window -t -1 \; previous-window
bind -n -r C-Right swap-window -t +1 \; next-window

bind -n C-j select-pane -L
bind -n C-k select-pane -D
bind -n C-l select-pane -U
bind -n C-ñ select-pane -R

bind -n -r M-Left   resize-pane -L +2
bind -n -r M-Down   resize-pane -D +2
bind -n -r M-Up     resize-pane -U +2
bind -n -r M-Right  resize-pane -R +2

#bind -n M-Tab   next-window
#bind -n M-BTab  previous-window

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6
bind -n M-7 select-window -t 7
bind -n M-8 select-window -t 8
bind -n M-9 select-window -t 9
bind -n M-0 select-window -t 10

## PLUGINS ##
set -g @plugin 'tmux-plugins/tpm'
#set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'dracula/tmux'

set -g @dracula-show-powerline true
#set -g @dracula-plugins "battery cpu-usage ram-usage time"
set -g @dracula-plugins "battery ram-usage time"
set -g @dracula-show-timezone false
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g @dracula-border-contrast true
set -g @dracula-show-empty-plugins false
set -g status-position top
set -g pane-border-status top
set -g pane-border-format ''

## TPM ##
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.local/share/tmux/plugins'
if "test ! -d ~/.local/share/tmux/plugins/tpm" \
   "run 'git clone https://github.com/tmux-plugins/tpm ~/.local/share/tmux/plugins/tpm && ~/.local/share/tmux/plugins/tpm/bin/install_plugins'"
run '~/.local/share/tmux/plugins/tpm/tpm'
