#####################
### CONFIGURATION ###
#####################

# PLUGINS
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'dracula/tmux'

set -g @dracula-show-powerline true

# SETTINGS
set -g default-command "/usr/bin/zsh"
set -g default-terminal 'xterm-256color'
set -ga terminal-overrides ',*:Tc'

# set -g default-terminal 'screen-256color'
# set -g default-terminal 'tmux-256color'
# set -g default-terminal 'tmux-256color'

# OVERRIDES
## This is for 256 colors

## This is for the cursor shape
# set -ga terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[ q'

set -g history-limit 10000
set -g allow-rename off
setw -g automatic-rename off
setw -g mode-keys vi
set -g base-index 1
set-option -g renumber-windows on
set-option -sg escape-time 10

unbind C-b
set -g prefix C-a
bind C-a send-prefix

unbind 'c'
unbind '"'
unbind '%'

# Move tabs
bind -r > swap-window -t -1 \; previous-window
bind -r < swap-window -t +1 \; next-window

# Buffer mode
bind Space copy-mode

# Reload config
bind r source-file ~/.config/tmux/tmux.conf \; display-message "Reloaded"

# Navigate
bind 'j' select-pane -L
bind 'k' select-pane -D
bind 'l' select-pane -U
bind 'ñ' select-pane -R

bind n new-window 
bind h split-window -h -c '#{pane_current_path}'
bind v split-window -v -c '#{pane_current_path}'
bind y setw synchronize-panes off
bind f resize-pane -Z

# POWERLINE
# source /usr/lib/python3.6/site-packages/powerline/bindings/tmux/powerline.conf
# if-shell 'env "$POWERLINE_CONFIG_COMMAND" tmux setup' '' 'run-shell "powerline-config tmux setup"'
# set -g status-left ''
# set -g status-interval 10

## THEMES
run-shell "~/.config/tmux/themes/nord/nord.tmux"
set -g status-position top
set -g status-justify centre
#set -g status-bg default
#set -g status-style bg=default
#set -g window-style bg=default
#set -g window-active-style bg=default

## PLUGINS
# git clone https://github.com/tmux-plugins/tpm ~/.local/share/tmux/tmp
# run '~/.local/share/tmux/tpm'
