[org/gnome/desktop/input-sources]
sources=[('xkb', 'es')]
xkb-options=['caps:ctrl_modifier']

[org/gnome/desktop/interface]
clock-show-date=true
clock-show-seconds=true
clock-show-weekday=false
show-battery-percentage=true
color-scheme='prefer-dark'
cursor-size=24
cursor-theme='Bibata-Modern-Ice'
document-font-name='JetBrainsMono Nerd Font 11'
font-name='JetBrainsMono Nerd Font 14'
gtk-theme='Catppuccin-Mocha-Standard-Peach-Dark'
icon-theme='BeautyLine'
monospace-font-name='JetBrainsMono Nerd Font 10'

[org/gnome/desktop/peripherals/touchpad]
tap-to-click=true
two-finger-scrolling-enabled=true

[org/gnome/desktop/wm/preferences]
num-workspaces=10
titlebar-font='JetBrainsMono Nerd Font Bold 11'

[org/gnome/mutter]
auto-maximize=false
center-new-windows=true
dynamic-workspaces=false
edge-tiling=false
overlay-key=''

[org/gnome/settings-daemon/plugins/media-keys]
custom-keybindings=['/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0/']

[org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/custom0]
binding='<Super>Return'
command="/bin/bash -c 'exec $HOME/.config/scripts/terminal.sh'"
name='Terminal'

[org/gnome/shell/extensions/forge]
css-last-update=uint32 37
dnd-center-layout='stacked'
preview-hint-enabled=true
stacked-tiling-mode-enabled=false
tabbed-tiling-mode-enabled=false
tiling-mode-enabled=true
window-gap-size=uint32 10
window-gap-size-increment=uint32 1

[org/gnome/desktop/wm/keybindings]
close=['<Super>q']
switch-windows=['<Super>k']
toggle-maximized=['<Super>t']
switch-to-workspace-1=['<Super>1']
switch-to-workspace-2=['<Super>2']
switch-to-workspace-3=['<Super>3']
switch-to-workspace-4=['<Super>4']
switch-to-workspace-5=['<Super>5']
switch-to-workspace-6=['<Super>6']
switch-to-workspace-7=['<Super>7']
switch-to-workspace-8=['<Super>8']
switch-to-workspace-9=['<Super>9']
switch-to-workspace-10=['<Super>0']
move-to-workspace-1=['<Super><Shift>1']
move-to-workspace-2=['<Super><Shift>2']
move-to-workspace-3=['<Super><Shift>3']
move-to-workspace-4=['<Super><Shift>4']
move-to-workspace-5=['<Super><Shift>5']
move-to-workspace-6=['<Super><Shift>6']
move-to-workspace-7=['<Super><Shift>7']
move-to-workspace-8=['<Super><Shift>8']
move-to-workspace-9=['<Super><Shift>9']
move-to-workspace-10=['<Super><Shift>0']

# move-to-workspace-left=['<Shift><Super>j']
# move-to-workspace-right=['<Shift><Super>ntilde']
# switch-to-workspace-left=['<Super>j']
# switch-to-workspace-right=['<Super>ntilde']
move-to-workspace-left=@as []
move-to-workspace-right=@as []
switch-to-workspace-left=@as []
switch-to-workspace-right=@as []

[org/gnome/shell/keybindings]
toggle-overview=['<Super>n', '<Super>m']
switch-to-application-1=@as []
switch-to-application-2=@as []
switch-to-application-3=@as []
switch-to-application-4=@as []
switch-to-application-5=@as []
switch-to-application-6=@as []
switch-to-application-7=@as []
switch-to-application-8=@as []
switch-to-application-9=@as []
focus-active-notification=@as []

[org/gnome/shell/extensions/forge/keybindings]
con-split-horizontal=['<Super>h']
con-split-vertical=['<Super>v']

window-focus-left=['<Super>j']
window-focus-right=['<Super>ntilde']
window-focus-up=['<Super>l']
window-focus-down=['<Super>k']

window-move-left=['<Shift><Super>j']
window-move-right=['<Shift><Super>ntilde']
window-move-up=['<Shift><Super>l']
window-move-down=['<Shift><Super>k']

mod-mask-mouse-tile='None'
con-split-layout-toggle=@as []
con-stacked-layout-toggle=@as []
con-tabbed-layout-toggle=@as []
con-tabbed-showtab-decoration-toggle=@as []
focus-border-toggle=@as []
prefs-tiling-toggle=@as []
window-gap-size-decrease=@as []
window-gap-size-increase=@as []

window-resize-bottom-decrease=@as []
window-resize-bottom-increase=@as []
window-resize-left-decrease=@as []
window-resize-left-increase=@as []
window-resize-right-decrease=@as []
window-resize-right-increase=@as []
window-resize-top-decrease=@as []
window-resize-top-increase=@as []

window-snap-center=@as []
window-snap-one-third-left=@as []
window-snap-one-third-right=@as []
window-snap-two-third-left=@as []
window-snap-two-third-right=@as []
window-swap-down=@as []
window-swap-last-active=@as []
window-swap-left=@as []
window-swap-right=@as []
window-swap-up=@as []
window-toggle-always-float=@as []
window-toggle-float=@as []
workspace-active-tile-toggle=@as []
