#!/usr/bin/env zsh

aws-ssm-connect() {
  local instance
  local instance_name instance_id region profile

  instance=$(cat $HOME/.aws/inventory | column -s ';' -t | fzf )
  [ -z "$instance" ] && return 0

  echo "$instance" | awk '{ print $1 }'

  instance_name=$(echo "$instance" |  awk '{print $1 }')
  instance_id=$(echo "$instance" |  awk '{print $2 }')
  region=$(echo "$instance" |  awk '{print $3 }')
  profile=$(echo "$instance" |  awk '{print $4 }')

  echo "-> Connect to ${instance_id} - ${instance_name}"
  echo "aws ssm start-session --target ${instance_id} --region ${region} --profile ${profile}" --cli-read-timeout 8000

  if [ -n "$1" ]; then
    eval ssh ${instance_id} -o ProxyCommand=\"aws ssm start-session --target ${instance_id} \
      --document-name AWS-StartSSHSession --parameters 'portNumber=22' \
      --region ${region} --profile ${profile}\"
  else
    eval aws ssm start-session --target ${instance_id} --region ${region} --profile ${profile}
  fi

  #ProxyCommand aws ssm start-session --target %h --document-name AWS-StartSSHSession --parameters 'portNumber=%p' --profile logalty
  # aws ssm start-session --target "Your Instance ID" --document-name AWS-StartPortForwardingSession --parameters "portNumber"=["80"],"localPortNumber"=["56789"]
}


