#!/usr/bin/zsh

dot() {
  command git --git-dir=$HOME/.local/share/settings --work-tree=$HOME "$@"
}

dot-get-windows-files() {
  local windows_user_home=$(echo $PATH | grep -io -P "/mnt/c/Users/.*?/" | head -1)

  [ -z "${windows_user_home}" ] && return 0
  [ ! -d "$HOME/.config/Windows" ] && mkdir -p $HOME/.config/Windows

  cp $windows_user_home/AppData/Roaming/Code/User/settings.json \
    $HOME/.config/Windows/code-user-settings.json

  cp $windows_user_home/AppData/Roaming/Code/User/keybindings.json \
    $HOME/.config/Windows/code-user-keybindings.json

  cp $windows_user_home/AppData/Local/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json \
    $HOME/.config/Windows/terminal-settings.json
}

status() {
  dot restore --staged . &>/dev/null

  # ADD WINDOWS FILE (WSL)
  dot-get-windows-files
  ###

  [ -e "$KUBECONFIG" ] && \
    sed "s/current-context:.*$/current-context: none/g" -i $KUBECONFIG

  # add
  # dot add $(< $HOME/.gitinclude | grep -v -e "^ *#" -e "^ *$" | tr '\n' ' ' | sed "s#\$HOME#$HOME#g")
  dot add -u
  for pattern in $(< $HOME/.gitinclude | grep -v -e "^ *#" -e "^ *$" | tr '\n' ' ' | sed "s#\$HOME#$HOME#g"); do
    eval dot add ${pattern} 2>/dev/null
  done

  # status
  dot status
}

save() {
  dot commit -m "Commit on '$(date '+%Y-%m-%d %H:%M:%S')'"
  dot push -u origin main
}

load() {
  dot pull
}
