#!/usr/bin/zsh

function kustomize-menu {
  local entry=$(find . -path "*/overlays/*" -type f -name kustomization.yaml | xargs -I@ dirname @ | fzf)
  [ -z "$entry" ] && return 0

  #print -z kubectl --context $(basename $entry) apply --server-side --force-conflicts -k ${entry}
  #print -z "kustomize build --enable-alpha-plugins ${entry} | kubectl --context $(basename $entry) apply --server-side --force-conflicts -f -"
  print -z "kustomize build --enable-helm ${entry} | kubectl --context $(basename $entry) apply --server-side --force-conflicts -f -"
}
