#!/usr/bin/zsh

function notes() {
  local notedir="$HOME/Documents/Notes"
  local remote="https://gitlab.com/MLR96/notes.git"

  ! type git &>/dev/null && return -1
  ! type nvim &>/dev/null && return -1

  [ ! -d "${notedir}" ] && \
    git clone ${remote} ${notedir}

  cd ${notedir}

  [ ! -d ".git" ] && return
  git remote | grep -q . || return

  [ -n "$TMUX" ]   && tmux rename-window "NOTES"
  [ -n "$ZELLIJ" ] && zellij action rename-tab "NOTES"

  git pull
  nvim home.md tasks.md inbox.md
  if git status | grep -q 'modified\|untracked'; then
    echo "Guardando y subiendo cambios..."
    git add .
    git commit -m "Saved at $(date '+%Y-%m-%d %H:%M:%S')"
    git push
  fi
}

# NOTES
# function notes() {
#   local notespath="$HOME/Documents/Wiki"
#   local repository=""
#
#   [ "$notespath/pages" ] && mkdir -p "$notespath/pages" &>/dev/null
#   [ "$notespath/assets" ] && mkdir -p "$notespath/assets" &>/dev/null
#
#   [ -n "$TMUX" ] && tmux rename-window 'NOTES'
#
#   # Run NeoVim
#   cd $notespath
#   [ -d ".git/" ] && git pull
#   nvim index.md
#   [ -d ".git/" ] && git status
#
#   # Save changes
#   #[ -n "$(git status | grep -i untracked)" ] && \
#   #[ -d ".git/" ] && \
#   #  git add . && \
#   #  git commit -m "$(date '+%Y-%m-%d %H:%M:%S')" && \
#   #  git push -u origin main
# }

