#!/user/bin/zsh
# vim: ft=zsh

function __pip_setup() {
  [ -d "${PYTHONVENV}" ] && return
  command python -m venv "${PYTHONVENV}"
}

function pip() {
  __pip_setup
  $PYTHONVENV/bin/pip "$@"
}

pip "$@"
