#!/usr/bin/zsh

function tm() {
    local session_name=$1

    # [ -z "$session_name" ] && session_name=$USER
    [ -z "$session_name" ] && session_name="0"

    if [ -n "$(tmux ls 2>/dev/null | grep $session_name:)" ]; then
        tmux attach-session -t $session_name
    else
        tmux -2 new-session -d -s $session_name -n HOME
        tmux attach-session -t $session_name
    fi
}


