#!/usr/bin/zsh

function tunnel-menu() {
  local cmd
  local opts=(
    "demodb:  ssh -L 1521:demo-db.cw9jeidr8a9e.eu-west-1.rds.amazonaws.com:1521 -N 52.50.61.78"
    "oradb01: kubectl --context demo -n default port-forward pods/forward-0 1522:1521"
    "logaltyQA: aws-tunnel 1523:logalty.chfbhhgsmzca.eu-south-2.rds.amazonaws.com:1521 i-04a7f8ed6a1c77a37"
    "releases: kubectl --context tools -n logalty port-forward pods/mysql-0 3306:3306"
  )

  cmd=$(printf '%s\n' "${opts[@]}" | fzf --layout=default)
  [ -z "$cmd" ] && return 0

  echo "-> $cmd"
  eval "$(echo $cmd | cut -d ":" -f 2-100000000 | sed 's/^ *//g')"
}
