#!/bin/bash
set -eE -o functrace

############################# VARIABLES #############################
readonly DESKCTL=$0
readonly SCRIPT_NAME=$(basename $0)
readonly SCRIPT_DIR=$(readlink -m $(dirname $0))
readonly CPU_NUMBER=$(grep -c ^processor /proc/cpuinfo)

# FIX nixGL
unset LD_LIBRARY_PATH
unset LIBGL_DRIVERS_PATH
unset LIBVA_DRIVERS_PATH
unset __EGL_VENDOR_LIBRARY_FILENAMES

############################# AUX FUNCTIONS #############################
fail() {
  echo "Failed at $1: $2"
  notify-send -t 0 "Hyprland Desktop" "hyprcmd: failed code at line $1: $2"
}

run() {
  echo "Running command: $@"
  hyprctl dispatch exec "$@" || /bin/true
}

############################# COMMANDS #############################

# INIT
cmd_init() {
  dbus-update-activation-environment --systemd --all

  # INSTALL
  ln -sf $HOME/.config/hypr/hyprcmd $HOME/.local/bin/deskcmd

  # RESOURCES
  cmd_resources

  # ionice -c 2 -n 0 -p $(pidof Hyprland)

  # BALOOCTL
  type balooctl &>/dev/null && \
    balooctl disable &>/dev/null

  # THEME
  hyprctl setcursor "Bibata-Modern-Ice" 28

  return 0
}

# DAEMON
daemon_check_battery() {
  local battery=$(cat /sys/class/power_supply/BAT0/capacity)
  local status=$(cat /sys/class/power_supply/BAT0/status)

  [[ ! $battery =~ ^[0-9]+$ ]] && battery=100

  [[ $battery -lt 20 ]] && [[ ! -e ~/.cache/daemon/notify ]] && \
    notify-send -u critical -t 0 "Low Battery" "Battery level is ${battery}%." && \
    touch ~/.cache/daemon/notify

  [[ $battery -gt 20 ]] && [[ -e ~/.cache/daemon/notify ]] && rm ~/.cache/daemon/notify

  # Power profile
  if [ ${status} = "Discharging" ]; then
    if [[ $battery -lt 50 ]]; then
      cmd_power_profile power-saver
    else
      cmd_power_profile balanced
    fi
  else
    cmd_power_profile balanced
  fi

}

cmd_daemon() {
  echo "[+] Starting desktop daemon..."
  set +e;trap '' ERR
  while true; do
    daemon_check_battery
    sleep 5
  done
}

# PORTALS
cmd_portals() {
  return 0
  pkill -f "xdg-desktop-portal" || /bin/true
  run "$HOME/.nix-profile/libexec/xdg-desktop-portal-hyprland"
  return 0
}

# PANEL
cmd_panel() {
  if type waybar &>/dev/null; then
    pkill waybar || /bin/true
    ln -sf $XDG_RUNTIME_DIR/hypr /tmp
    run "waybar -c $HOME/.config/waybar/${XDG_CURRENT_DESKTOP,,}.json -s $HOME/.config/waybar/${XDG_CURRENT_DESKTOP,,}.css"
  fi

  if type nm-applet &>/dev/null; then
    pkill nm-applet || /bin/true
    run "nm-applet"
  fi

  return 0
}

# NOTIFY
cmd_notify_daemon() {
  if type mako &>/dev/null; then
    pkill mako || /bin/true
    run "mako"
  fi
}

# WALLPAPER
cmd_wallpaper() {
  local cache_file="$HOME/.cache/wallpaper"
  local cached="$(cat ${cache_file})"
  local wallpapers_path="$HOME/.local/share/backgrounds"
  local wallpaper="${wallpapers_path}/$(ls ${wallpapers_path} | shuf -n 1)"

  if type swww &>/dev/null; then
    if ! pgrep -x "swww-daemon" > /dev/null; then
      pkill swww || /bin/true
      run "swww-daemon --format 'xrgb'"
      [ -e "${cached}" ] && wallpaper=${cached}
      swww img ${wallpaper}
    else
      swww img ${wallpaper} \
        --transition-type center \
        --transition-fps 60 \
        --transition-step 50 \
        --transition-duration 1
      echo "${wallpaper}" > ${cache_file}
    fi
  fi

  # if type wal &>/dev/null; then
  #   wal -i ${wallpaper}
  # fi

  return 0
}

# DISTROBOXES
cmd_distroboxes() {
  if type distrobox &>/dev/null; then
    for name in $(distrobox list --no-color | awk -F'|' '{print $2}' | grep -v "NAME" ); do
      distrobox enter ${name} -- echo
    done

  fi

  return 0
}

# LOCK
cmd_lock() {
  local image=$(ls ~/.local/share/backgrounds | shuf -n 1)
  exec swaylock -i ~/.local/share/backgrounds/${image}
  return 0
}

# SCREENSHOT
cmd_screenshot() {
  sleep 0.2
  grim -g "$(slurp || true)" - | wl-copy -t image/png
}

# TERMINAL
terminal_toggle() {
  local namespace="terminal"
  local window=$(hyprctl clients -j | jq ".[] | select(.workspace.name == \"special:${namespace}\" )")
  [ -z "${window}" ] && \
    exec hyprctl dispatch exec "[floating;workspace special:${namespace}] kitty -o initial_window_width=1600 -o initial_window_height=800"
    #exec hyprctl dispatch exec "[floating;workspace special:${namespace}] foot -w 1400x600"
  hyprctl dispatch togglespecialworkspace "${namespace}"
  return 0
}

terminal_shell() {
  local multiplexer="${1-true}"
  local session="${2-0}"

  export ZDOTDIR=$HOME/.config/zsh

  if [ "${multiplexer}" = "true" ]; then
    if type zellij &>/dev/null; then
      { zellij attach "${session}" || exec zellij -s "${session}"; }; exit 0
    fi
    if type tmux &>/dev/null; then
      { tmux attach-session -t "${session}" || exec tmux -2 new-session -s "${session}" -n 'HOME'; }; exit 0
    fi
  fi

  type zsh &>/dev/null && exec zsh

  return 0
}

cmd_terminal() {
  local command="${1-start}"; shift || /bin/true

  if [ "${command}" = "toggle" ]; then
    terminal_toggle
  elif [ "${command}" = "shell" ]; then
    terminal_shell "$@"
  elif [ "${command}" = "start" ]; then
    local uuid=$(tr -dc 'a-z0-9' < /dev/urandom | head -c 12)
    type alacritty &>/dev/null \
      && exec hyprctl dispatch exec "systemd-run --user --scope --unit=app-terminal-${uuid}.scope --slice=app.slice -- alacritty -e deskcmd terminal shell"

    type wezterm &>/dev/null \
      && exec wezterm start --always-new-process -- ${DESKCTL} terminal shell

    type foot &>/dev/null \
      && exec foot -- ${DESKCTL} terminal shell false
  fi

  return 0
}

# MENU
menu_launcher() {
  #type rofi &>/dev/null && exec systemd-run --user --scope --slice=app.slice -- rofi -show drun
  type rofi &>/dev/null && exec rofi -show drun

  [ -n "$(pidof wofi)" ] && return 0

  exec wofi -i --show drun \
    --no-actions \
    --normal-window \
    --allow-images \
    --sort-order=alphabetical \
    --parse-search \
    --lines=10 --columns=10 \
    -s $HOME/.config/sway/wofi.css
    #--matching=fuzzy \

  return 0
}

menu_power() {
  if type wlogout &>/dev/null; then
    pkill wlogout || /bin/true
    exec wlogout -b 2 -c 20 -r 20 -m 100
  fi

  set +eE
  local choice=$(echo -e "Lock|Exit|Reboot|Poweroff|None" | rofi -dmenu -sep '|' -p "Option" -i)
  echo ${choice,,}

  [ "${choice,,}" = "lock" ] && $0 lock
  [ "${choice,,}" = "exit" ] && $0 exit
  [ "${choice,,}" = "reboot" ] && systemctl reboot
  [ "${choice,,}" = "poweroff" ] && systemctl poweroff -i

  exit 0
}

cmd_menu() {
  local menu="${1-launcher}"; shift || /bin/true
  [[ "${menu}" == "launcher" ]] && menu_launcher
  [[ "${menu}" == "power" ]] && menu_power
  [[ "${menu}" == "exit" ]] && menu_power
}

# THEME
cmd_theme() {
  local gnome_schema="org.gnome.desktop.interface"
  local cursor_theme="bibata-modern-ice-cursors"
  local gtk_theme="Catppuccin-Mocha-Standard-Peach-Dark"
  local icon_theme="cupertino-sonoma-icons"
  local font_theme="JetBrainsMono Nerd Font 12"

  [ -d "$HOME/.local/share/icons/${cursor_theme}" ] && \
    hyprctl setcursor "${cursor_theme}" 32 \

  ! type gsettings &>/dev/null && exit 0

  [ -d "$HOME/.local/share/icons/${cursor_theme}" ] && \
    gsettings set ${gnome_schema} cursor-theme "${cursor_theme}"

  [ -d "$HOME/.local/share/themes/${gtk_theme}" ] && \
    gsettings set ${gnome_schema} gtk-theme "${gtk_theme}" && \
    gsettings set ${gnome_schema} color-scheme 'prefer-dark'

  [ -d "$HOME/.local/share/themes/icons/${icon_theme}" ] && \
    gsettings set ${gnome_schema} icon-theme "${icon_theme}"

  gsettings set ${gnome_schema} font-name "${font_theme}"

  return 0
}

# VOLUME
cmd_volume() {
  local cmd="${1}"

  local volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | tr -d '.' | grep -o "[0-9]\+" | sed 's/^0*//g')

  [[ "${cmd}" == "inc" ]] && \
    wpctl set-volume @DEFAULT_AUDIO_SINK@ $(($volume-$volume%5+5))%

  [[ "${cmd}" == "dec" ]] && \
    wpctl set-volume @DEFAULT_AUDIO_SINK@ $(($volume-$volume%5-5))%

  return 0
}

# EXIT
cmd_exit() {
  hyprctl dispatch exit 0
}

# WALLPAPER TIMER
cmd_wallpaper_timer() {
  local timer="${1-30}"
  while true; do
    sleep $timer
    cmd_wallpaper
  done
}

# POWER PROFILE
cmd_power_profile () {
  local profile="$1" # balanced power-saver performance
  local notify="$2"
  local current

  if type powerprofilesctl &>/dev/null; then
    current=$(powerprofilesctl get)
    if [ $profile != $current ]; then
    powerprofilesctl set $profile
    [ -z "$notify" ] && \
      notify-send -u low "Power Profile" "${profile}"
    fi
  fi

  return 0
}

# SET RESOURCES
cmd_resources() {
  echo "[+] Setting resources.."

  # POWERPROFILE
  cmd_power_profile balanced 1

  # systemctl set-property system.slice CPUShares=4096 IOWeight=400
  systemctl --user set-property --runtime session.slice CPUWeight=800 MemoryMin=1G MemoryLow=2G ManagedOOMPreference=omit IOWeight=400
  systemctl --user set-property --runtime app.slice MemoryHigh=10G MemoryMax=12G ManagedOOMMemoryPressureLimit=50%

  set_scope_resources() {
    local scope=$1; shift
    mkdir -p /run/user/${UID}/systemd/user.control/${scope}.d
    # rm -r /run/user/${UID}/systemd/user.control/${scope}.d/*

    case "$scope" in
      *.service) echo "[Service]" > /run/user/${UID}/systemd/user.control/${scope}.d/90-Resources.conf ;;
      *) echo "[Scope]" > /run/user/${UID}/systemd/user.control/${scope}.d/90-Resources.conf ;;
    esac

    for property in ${@}; do
      echo "${property}" >> /run/user/${UID}/systemd/user.control/${scope}.d/90-Resources.conf
    done
  }

  # Falta el terminal?
  set_scope_resources "app-flatpak-org.mozilla.firefox-.scope" CPUWeight=400
  set_scope_resources "app-flatpak-com.microsoft.Edge-.scope" CPUWeight=200
  set_scope_resources "app-terminal-.scope" CPUQuota="$((50 * ${CPU_NUMBER}))%"
  set_scope_resources "xdg-desktop-portal-wlr.service" CPUWeight=200
  set_scope_resources "zellij.scope" CPUWeight=25 CPUQuota="$((50 * ${CPU_NUMBER}))%"
  set_scope_resources "crun-buildah-.scope" CPUWeight=25 CPUQuota="$((50 * ${CPU_NUMBER}))%"
  # set_scope_resources "libpod-.scope" CPUWeight=25 CPUQuota="$((50 * ${CPU_NUMBER}))%"

  systemctl --user daemon-reload
}

# HELP
cmd_help() {
  cat <<- EOF
  Commands:
    init                         # Initialize desktop environment
    portals                      # Start/Restart xdg-desktop-portals
    panel                        # Start desktop panel
    wallpaper                    # Rotate/Set wallpaper
    lock                         # Lock screen
    screenshot                   # Take a screenshot
    terminal [start|shell|toggle]
    menu [app|power]
    volume [inc|dec|mute]
    micro [inc|dec|mute]
    flatpak install
    distrobox install
    resources
    notify-daemon
    exit                         # Exit from desktop
EOF
}

main() {
  local command="${1-help}"; shift
  local func="cmd_${command//-/_}"

  trap 'fail ${LINENO} "${BASH_COMMAND}"' ERR

  [[ ! -d ~/.cache/daemon ]] && mkdir -p ~/.cache/daemon

  # Commands
  case "${command}" in
    shutdown) systemctl poweroff -i;;
    reboot) systemctl reboot;;
    *)
      if declare -F ${func} > /dev/null; then
        "${func}" "${@}"
      else
        help
      fi
      ;;
  esac

  return 0
}

main "$@"
