#!/usr/bin/zsh

# ZSH
# export ZDOTDIR=$HOME/.config/zsh
export KEYTIMEOUT=1

export PATH=${PATH}:${HOME}/.config/scripts
export FPATH=${FPATH}:${HOME}/.config/zsh/functions

# SHELL
export HOSTNAME=$(hostname)
export EDITOR=nvim
# export TERM=xterm-256color
export PATH=${PATH}:/usr/local/bin
export PATH=${PATH}:${HOME}/.local/bin
export XDG_STATE_HOME=$HOME/.local/share/state

# SPACESHIP
export SPACESHIP_CONFIG="$HOME/.config/zsh/spaceship.zsh"

# PASS
export GNUPGHOME="$HOME/.config/gnupg"
export PASSWORD_STORE_DIR="$HOME/.local/share/vault"
export PASSWORD_STORE_CLIP_TIME=8

# FZF - Catppuccin Mocha
FZF_DEFAULT_OPTS=""
FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} -m --ansi --layout=reverse --inline-info"
FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --prompt='» ' --pointer='█' --marker='█'"
FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color=bg+:#313244,bg:#1e1e2e,spinner:#f5e0dc,hl:#f38ba8"
FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color=fg:#cdd6f4,header:#f38ba8,info:#cba6f7,pointer:#f5e0dc"
FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color=marker:#b4befe,fg+:#cdd6f4,prompt:#cba6f7,hl+:#f38ba8"
FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color=selected-bg:#45475a,border:#313244,label:#cdd6f4"
export FZF_DEFAULT_OPTS

# AWS
export AWS_PROFILE="none"

# KUBERNETES
export KUBECONFIG="$HOME/.config/kube/config"
export KUBE_EDITOR="nvim"
export HELM_CONFIG_HOME="$HOME/.config/helm"

# ANSIBLE
export ANSIBLE_CONFIG=$HOME/.config/ansible.cfg

# TERRAFORM
export TF_PLUGIN_CACHE_DIR="$HOME/.local/share/terraform/plugin-cache"
[[ -d "$TF_PLUGIN_CACHE_DIR" ]] || mkdir -p "$TF_PLUGIN_CACHE_DIR"

# PYTHON
export PYLINTRC="$HOME/.config/pylintrc"

# GO
export GOPATH="$HOME/.local/share/go"
export PATH=${PATH}:${GOPATH}/bin
export GOMAXPROCS=4

# RUST
export RUSTUP_HOME="$HOME/.local/share/rustup"

# NODEJS
export NPM_CONFIG_PREFIX="$HOME/.local"

# JAVA
export M2_HOME="$HOME/.local/share/maven"

# ANDROID
# export ANDROID_HOME=${HOME}/.local/share/android/sdk
# export ANDROID_USER_HOME=${HOME}/.local/share/android
# export ANDROID_AVD_HOME=${ANDROID_USER_HOME}/avd
# export ANDROID_JAVA_HOME=/usr/lib/jvm/java-17-openjdk
# # export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1
# export PATH=${PATH}:${ANDROID_HOME}/tools
# export PATH=${PATH}:${ANDROID_HOME}/tools/bin
# export PATH=${PATH}:${ANDROID_HOME}/platform-tools
# export PATH=${PATH}:${ANDROID_HOME}/emulator
# export PATH=${PATH}:${ANDROID_HOME}/cmdline-tools/latest/bin

# FLUTTER
export FLUTTER_HOME=${HOME}/.local/share/flutter/default
export PATH=${PATH}:${FLUTTER_HOME}/bin
export PATH=${PATH}:$HOME/.pub-cache/bin

# RUBY
export GEM_HOME=$HOME/.local/share/ruby

# PODMAN
export DOCKER_HOST="unix:///run/user/$UID/podman/podman.sock"

# BREW
[[ "$(uname)" == "Darwin" ]] && \
  export PATH=${PATH}:/opt/homebrew/bin:/opt/podman/bin

# NIX
export PATH=${PATH}:${HOME}/.nix-profile/bin

# TLS (Linux)
# El tooling instalado con nix no busca el trust store del host por diseño:
# se le apunta al bundle del sistema, probando las rutas habituales (la
# canónica de Fedora, su symlink de compatibilidad y la de Debian/Ubuntu).
# El bloque NETSKOPE de debajo lo sobreescribe cuando aplica.
for ca_bundle in /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem \
  /etc/pki/tls/certs/ca-bundle.crt \
  /etc/ssl/certs/ca-certificates.crt; do
  if [[ -e $ca_bundle ]]; then
    export SSL_CERT_FILE="$ca_bundle"
    break
  fi
done
unset ca_bundle

# NETSKOPE
# Add netskope CA cert to aws cli if we are working with netskope: Logalty
if [[ -e $HOME/.local/share/certificates/netskope.crt ]]; then
  # AWS CLI
  export AWS_CA_BUNDLE="$HOME/.local/share/certificates/netskope.crt"
  # PYTHON REQUESTS
  export REQUESTS_CA_BUNDLE="$HOME/.local/share/certificates/netskope.crt"
  # CURL
  export CURL_CA_BUNDLE="$HOME/.local/share/certificates/netskope.crt"
  # NODEJS
  export NODE_EXTRA_CA_CERTS="$HOME/.local/share/certificates/netskope.crt"
  # GIT
  export GIT_SSL_CAINFO="$HOME/.local/share/certificates/netskope.crt"
  # OPENSSL
  export SSL_CERT_FILE="$HOME/.local/share/certificates/netskope.crt"
  # JAVA
  export JAVA_TOOL_OPTIONS="-Djavax.net.ssl.trustStore=$HOME/.local/share/certificates/netskope.jks -Djavax.net.ssl.trustStorePassword=changeit"
fi

# PASSWORD
[[ -e $HOME/.local/share/environment.zsh ]] && source $HOME/.local/share/environment.zsh

typeset -U path
typeset -U fpath
