#!/usr/bin/zsh

# ZSH
# export ZDOTDIR=$HOME/.config/zsh
export KEYTIMEOUT=1

export PATH=${PATH}:${HOME}/.config/scripts
export FPATH=${FPATH}:${HOME}/.config/zsh/functions

# SHELL
export SHELL=/usr/bin/zsh
export HOSTNAME=$(hostname)
export EDITOR=nvim
export TERM=xterm-256color

# XDG
export XDG_STATE_HOME=$HOME/.local/share/state

# SPACESHIP
export SPACESHIP_CONFIG="$HOME/.config/zsh/spaceship.zsh"

# PASS
export GNUPGHOME="$HOME/.config/gnupg"
export PASSWORD_STORE_DIR="$HOME/.local/share/vault"
export PASSWORD_STORE_CLIP_TIME=8

# FZF
FZF_DEFAULT_OPTS=""
FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} -m --ansi --layout=reverse --inline-info"
FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --prompt='➤ ' --pointer='➤' --marker='➤'"
FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color 'fg:-1,bg:-1,hl:#fab387'"
FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color 'fg+:#b4befe,bg+:-1,hl+:#fab387'"
FZF_DEFAULT_OPTS="${FZF_DEFAULT_OPTS} --color 'prompt:166'"
export FZF_DEFAULT_OPTS

# AWS
export AWS_PROFILE="none"
# Add netskope CA cert to aws cli if we are working with netskope: Logalty
if [[ -e $HOME/.local/share/certificates/netskope.crt ]]; then
  export AWS_CA_BUNDLE="$HOME/.local/share/certificates/netskope.crt"
  export REQUESTS_CA_BUNDLE="$HOME/.local/share/certificates/netskope.crt"
fi

# KUBERNETES
export KUBECONFIG="$HOME/.config/kube/config"
export KUBE_EDITOR="nvim"
export HELM_CONFIG_HOME="$HOME/.config/helm"

# ANSIBLE
export ANSIBLE_CONFIG=$HOME/.config/ansible.cfg

# TERRAFORM
export TF_PLUGIN_CACHE_DIR="$HOME/.local/share/terraform/plugin-cache"

# PYTHON
export PYLINTRC="$HOME/.config/pylintrc"

# GO
export GOPATH="$HOME/.local/share/go"
export PATH=${PATH}:${GOPATH}/bin
export GOMAXPROCS=4

# RUST
export RUSTUP_HOME="$HOME/.local/share/rustup"

# NODEJS
export NPM_CONFIG_PREFIX="$HOME/.local"

# JAVA
export M2_HOME="$HOME/.local/share/maven"

# ANDROID
export ANDROID_HOME=${HOME}/.local/share/android/sdk
export ANDROID_USER_HOME=${HOME}/.local/share/android
export ANDROID_AVD_HOME=${ANDROID_USER_HOME}/avd
export ANDROID_JAVA_HOME=/usr/lib/jvm/java-17-openjdk
# export ANDROID_EMULATOR_USE_SYSTEM_LIBS=1
export PATH=${PATH}:${ANDROID_HOME}/tools
export PATH=${PATH}:${ANDROID_HOME}/tools/bin
export PATH=${PATH}:${ANDROID_HOME}/platform-tools
export PATH=${PATH}:${ANDROID_HOME}/emulator
export PATH=${PATH}:${ANDROID_HOME}/cmdline-tools/latest/bin

# FLUTTER
export FLUTTER_HOME=${HOME}/.local/share/flutter/default
export PATH=${PATH}:${FLUTTER_HOME}/bin
export PATH=${PATH}:$HOME/.pub-cache/bin

# RUBY
export GEM_HOME=$HOME/.local/share/ruby

# PATH
export PATH=${PATH}:/usr/local/bin
export PATH=${PATH}:${HOME}/.local/bin

# PODMAN
export DOCKER_HOST="unix:///run/user/$UID/podman/podman.sock"

# BREW
[[ "$(uname)" == "Darwin" ]] && \
  export PATH=${PATH}:/opt/homebrew/bin

# NIX
export PATH=${PATH}:${HOME}/.nix-profile/bin

typeset -U path
typeset -U fpath
