#!/usr/bin/zsh

# zmodload zsh/zprof

#### SETTINGS
HISTSIZE=10000
SAVEHIST=10000
HISTFILE="$HOME/.zhistory"
HISTIGNORE='pass *'
ZSH_AUTOSUGGEST_STRATEGY=(history completion)

umask 022

typeset -U path
typeset -U fpath

autoload -U colors && colors
autoload -U compinit && compinit
autoload -Uz promptinit && promptinit
autoload -U select-word-style && select-word-style bash
zstyle 'completion:*' menu select
#emulate sh

# Auto completion options
setopt autocd			# Imply cd when directory path is supplied
setopt automenu			# Automatically use menu completion on 2nd tab
setopt menucomplete		# Cycle though autocomplete options

# History options
setopt appendhistory	# Append history file rather than replace it
setopt extendedhistory	# Save each commands time stamp
setopt histfindnodups	# Ignore duplicates when searching
setopt histignoredups	# Ignore duplicate simultaneous events
setopt histignorespace	# Ignore commands that being with space
setopt histsavenodups	# Ignore old duplicate commands on save

setopt completealiases

#### BINDKEYS
bindkey -e
bindkey "^[[H"  beginning-of-line
bindkey "^[[F"  end-of-line
bindkey "^[[3~" delete-char
bindkey '^R' history-incremental-search-backward
# bindkey "\033[1~" beginning-of-line
# bindkey "\033[4~" end-of-line

# Clear screen A-h
# bindkey '\eh' clear-screen

#  # Move
#  bindkey -s '\eñ' '^[[C'
#  bindkey -s '\ej' '^[[D'
#  bindkey -s '\ek' '^[[B'
#  bindkey -s '\el' '^[[A'

#### PLUGINS
# Ubuntu
[ -e /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ] && \
    source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh

[ -e /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && \
    source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Archlinux
[ -e /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh ] && \
    source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh

[ -e /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh ] && \
    source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh

# Nix
[ -e ~/.nix-profile/share/zsh-autosuggestions/zsh-autosuggestions.zsh ] && \
    source ~/.nix-profile/share/zsh-autosuggestions/zsh-autosuggestions.zsh

[ -e ~/.nix-profile/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && \
    source ~/.nix-profile/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Dotfiles
[ -e "$HOME/.config/zsh/plugins/fzf-history-search.zsh" ] && \
    source $HOME/.config/zsh/plugins/fzf-history-search.zsh

# PROMPT
prompt redhat
type starship &>/dev/null && \
  eval "$(starship init zsh)"

# AUTOCOMPLETE
[[ $commands[kubectl] ]] && \
  source <(kubectl completion zsh)

# TMUX
#[ -n "${TMUX_POPUP}" ] && setopt ignore_eof

# PYTHON
#[ -n "${PYTHONVENV}" ] && [ ! -d "${PYTHONVENV}" ] && \
#  echo "-> Creating local virtualenv for python" && command python -m venv "${PYTHONVENV}"

#[ -e ${PYTHONVENV}/bin/activate ] && \
#  source ${PYTHONVENV}/bin/activate

#[ "$PIPENV_ACTIVE" -eq 1 ] && deactivate


# ALIASES
source $HOME/.config/zsh/aliases.zsh
autoload -Uz $HOME/.config/zsh/functions/*(.:t); all.zsh

# FIX nixGL
unset LD_LIBRARY_PATH
unset LIBGL_DRIVERS_PATH
unset LIBVA_DRIVERS_PATH
unset __EGL_VENDOR_LIBRARY_FILENAMES

# opencode
export PATH=/Users/miguel.lopez/.opencode/bin:$PATH
