#!/usr/bin/zsh

DISK_DEVICE=""
PARTITION_BOOT_TYPE="fat32"
FS_BTRFS_OPTS="defaults,compress=ztd,ssd,noatime,autodefrag,space_cache=v2"
FS_EXT4_OPTS="defaults,noatime,discard"
REINSTALL="true"

BOOTLOADER="systemd"
HOSTNAME="laptop"
NTP="time.google.com"

USER_ID=2000
USER_NAME="mlr"
USER_FULL_NAME="MLR96"
USER_PATH="/home/$USER_NAME"
USER_SHELL="/bin/bash"

help() {
  echo "archlinux distro-install /dev/sda"
  exit 0
}

distro-install() {
  DISK_DEVICE=$1
  [ ! -b "$DISK_DEVICE" ] && help

  read -p "-> REINSTALL ARCHLINUX WITHOUT REMOVE DATA (Y/N): " answer
  [ "$answer" = "Y" ] && break

  #wipefs --force --all ${DEVICE} > /dev/null
}

distro-configure() {
  echo ""
}

update() {
  sudo reflector --verbose --latest 5 --sort rate --protocol https --save /etc/pacman.d/mirrorlist
}

upgrade() {
  sudo pacman -Syu
  type yay &> /dev/null && yay -Syua
  sudo pacman -Scc
}

install() {
  sudo pacman --needed -S "$@"
}

uninstall() {
  sudo pacman -Rns "$@"
}

archlinux() {
  local command="$1"; shift

  if declare -f "$command" >/dev/null 2>&1; then
    "$command" "$@"
  fi
}

archlinux "$@"
