---
k9s:
  liveViewAutoRefresh: false
  screenDumpDir: /home/mlr/.local/share/state/k9s/screen-dumps
  refreshRate: 2
  maxConnRetry: 3
  readOnly: false
  noExitOnCtrlC: false
  skipLatestRevCheck: false
  disablePodCounting: false
  ui:
    enableMouse: false
    headless: false
    logoless: false
    crumbsless: false
    reactive: false
    noIcons: false
    skin: catppuccin-mocha-transparent
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 1000
    buffer: 5000
    sinceSeconds: -1
    fullScreen: false
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      warn: 90
      critical: 95
    memory:
      warn: 90
      critical: 95
