k9s:
  liveViewAutoRefresh: false
  refreshRate: 5
  maxConnRetry: 5
  enableMouse: false
  enableImageScan: false
  headless: false
  logoless: true
  crumbsless: true
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  skipLatestRevCheck: false
  logger:
    tail: 1000
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: false
    showTime: false
  currentContext: demo
  currentCluster: demo
  keepMissingClusters: false
  clusters:
    demo:
      namespace:
        active: all
        lockFavorites: true
        favorites:
        - all
        - kube-system
        - kube-public
        - kube-node-lease
        - default
        - ingress
      view:
        active: pods
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
    tools:
      namespace:
        active: all
        lockFavorites: true
        favorites:
        - all
        - default
        - ingress
      view:
        active: pods
      featureGates:
        nodeShell: false
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 80
    memory:
      critical: 90
      warn: 80
  screenDumpDir: /tmp/k9s-screens-mlr
  disablePodCounting: false
