return {
	"nvim-treesitter/nvim-treesitter",
	main = "nvim-treesitter.configs",
	lazy = false,
	opts = {
		sync_install = true,
		auto_install = true,
		ignore_install = { "phpdoc" },
		highlight = {
			enable = true,
			disable = { "css" },
		},
		autopairs = {
			enable = true,
		},
		indent = { enable = true, disable = { "python", "css" } },
		ensure_installed = {
			"bash",
			"c",
			"javascript",
			"json",
			"lua",
			"python",
			"typescript",
			"tsx",
			"css",
			"rust",
			"java",
			"yaml",
			"markdown",
			"markdown_inline",
			"hcl",
			"http",
			"json",
			"sql",
			"terraform",
		},
	},
	enabled = vim.g.plugins.nvim_treesitter,
}
