#!/usr/bin/env bash
set -e

# Primero, definimos el nombre de la rama actual
#current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ -z "$(git config user.email)" ]; then
  echo Your name and email address were configured automatically based
  echo on your username and hostname. Please check that they are accurate.
  echo You can suppress this message by setting them explicitly:
  echo
  echo     git config --global user.name "Your Name"
  echo     git config --global user.email you@example.com
  exit -1
fi

# # Luego, traemos los últimos cambios del repositorio remoto sin cambiar nuestros archivos locales
# if git show-ref --verify --quiet refs/remotes/origin/$current_branch; then
#   git fetch
#
#   # Comprobamos si hay diferencias entre la rama actual y su contraparte remota
#   if ! git diff --quiet HEAD origin/$current_branch; then
#       echo "Hay commits pendientes en la rama remota. "
#       echo "Por favor, haz primero un pull."
#       exit -1
#   fi
# fi

exit 0
