# vim: ft=swayconfig

bar {
    swaybar_command waybar
}

# OUTPUTS
exec_always swaycmd monitor
exec_always nm-applet

### AUTOSTART
exec swaycmd autostart
#exec ~/.config/sway/scripts/autostart.sh

# exec_always waybar -c ~/.config/sway/waybar.conf -s ~/.config/sway/waybar.css




