# vim: ft=swayconfig

### Output configuration
# output * bg $wallpaper fill
#output * bg #1e1e2e solid_color
output eDP-1 resolution 1920x1080 position 0,0 scale 1

input "type:keyboard" {
    xkb_layout es
    #xkb_variant mac

    xkb_options ctrl:nocaps
    # xkb_options caps:ctrl_modifier
    # xkb_options caps:none
    # xkb_options grp:alt_shift_toggle
}

input "type:touchpad" {
  dwt enabled
  tap enabled
  natural_scroll enabled
  middle_emulation enabled
}

bindswitch --reload --locked lid:on exec swaycmd monitor
bindswitch --reload --locked lid:off exec swaycmd monitor

