# vim: ft=swayconfig

### RULES
# for_window [app_id="menu"] floating enable; resize set 600 1015; move position 0 0
# for_window [app_id="menu"] floating enable; resize set 1000 600; move position center
for_window [app_id="menu"] floating enable; resize set 600 800; move position center
for_window [app_id="pinentry-qt"] floating enable
for_window [app_id="xdg-desktop-portal-gtk"] floating enable; resize set 1500 800; move position center
for_window [app_id="imv"] floating enable; move position center
for_window [app_id="mpv"] floating enable; move position center

# Vivaldi
# for_window [title="^Ajustes de Vivaldi:.*$"] floating enable

# Workspaces
for_window [app_id="brave-browser"] move to workspace $ws2
#for_window [class="Vivaldi-stable"] move to workspace $ws2
#for_window [class="Chromium"] move to workspace $ws2

for_window [app_id="google-chrome"] move to workspace $ws3
#for_window [app_id="telegramdesktop"] move to workspace $ws3
#for_window [class="TelegramDesktop"] move to workspace $ws3
#for_window [app_id="thunderbird"] move to workspace $ws3
#for_window [instance="teams.microsoft.com"] move to workspace $ws3
#for_window [instance="web.whatsapp.com"] move to workspace $ws3
#for_window [instance="join.zoom.us"] move to workspace $ws3
#
#for_window [class="xfreerdp"] move to workspace $ws8
# for_window [name="FreeRDP"] move to workspace $ws8

for_window [app_id="org.keepassxc.KeePassXC"] move to workspace $ws7

#for_window [instance="open.spotify.com"] move to workspace $ws9
#for_window [instance="ticktick.com"] move to workspace $ws10
#for_window [instance="www.notion.so.*"] move to workspace $ws10
#for_window [class="obsidian"] move to workspace $ws10
