# vim: ft=swayconfig

xwayland disabled
font pango:Fira Code, Bold 14
gaps inner 10
gaps outer 10
workspace_layout default
title_align center
default_border pixel 2
default_floating_border pixel 2
hide_edge_borders none

# titlebar_border_thickness 0
# titlebar_padding 1
# hide_edge_borders smart

# CURSORS
seat seat0 xcursor_theme Bibata-Modern-Ice


